// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package messagepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SimpleMessage struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Number               bool     `protobuf:"varint,3,opt,name=Number,proto3" json:"Number,omitempty"`
	List                 []int32  `protobuf:"varint,4,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleMessage) Reset()         { *m = SimpleMessage{} }
func (m *SimpleMessage) String() string { return proto.CompactTextString(m) }
func (*SimpleMessage) ProtoMessage()    {}
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *SimpleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleMessage.Unmarshal(m, b)
}
func (m *SimpleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleMessage.Marshal(b, m, deterministic)
}
func (m *SimpleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleMessage.Merge(m, src)
}
func (m *SimpleMessage) XXX_Size() int {
	return xxx_messageInfo_SimpleMessage.Size(m)
}
func (m *SimpleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleMessage proto.InternalMessageInfo

func (m *SimpleMessage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SimpleMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SimpleMessage) GetNumber() bool {
	if m != nil {
		return m.Number
	}
	return false
}

func (m *SimpleMessage) GetList() []int32 {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*SimpleMessage)(nil), "SimpleMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x8a, 0xe7, 0xe2, 0x0d, 0xce, 0xcc,
	0x2d, 0xc8, 0x49, 0xf5, 0x85, 0x08, 0x0b, 0xf1, 0x71, 0x31, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0xb0, 0x06, 0x31, 0x79, 0xa6, 0x08, 0x09, 0x71, 0xb1, 0xf8, 0x25, 0xe6, 0xa6, 0x4a, 0x30,
	0x29, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x62, 0x5c, 0x6c, 0x7e, 0xa5, 0xb9, 0x49, 0xa9,
	0x45, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x50, 0x1e, 0x48, 0x6d, 0x4e, 0x66, 0x71, 0x89,
	0x04, 0x8b, 0x02, 0xb3, 0x06, 0x6b, 0x10, 0x98, 0xed, 0xc4, 0x1d, 0xc5, 0x09, 0xb5, 0xb1, 0x20,
	0x29, 0x89, 0x0d, 0x6c, 0xa9, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x66, 0xf8, 0x97, 0x30, 0x85,
	0x00, 0x00, 0x00,
}
